name: Generate GitHub Trophies

on:
  schedule:
    - cron: "30 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Trophy
        uses: ryo-ma/github-profile-trophy@master
        with:
          username: tarunyachaudhary
          output_path: assets/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: tokyonight

      - name: Commit Trophy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/trophy.svg
          git commit -m "Update GitHub trophies" || exit 0
          git push